# Generated by Django 5.2 on 2025-04-09 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='abertura',
            new_name='abertura_caixa',
        ),
        migrations.RenameField(
            model_name='caixa',
            old_name='fechamento',
            new_name='fechamento_caixa',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
