# Generated by Django 5.2 on 2025-04-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_rename_abertura_caixa_abertura_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='forma',
            field=models.CharField(blank=True, choices=[('DNH', 'DINHEIRO'), ('PIX', 'PIX'), ('CRC', 'CARTÃO DE CRÉDITO'), ('CRD', 'CARTÃO DE DÉBITO'), ('CHA', 'CHEQUE PRÉ'), ('CHP', 'CHEQUE PÓS')], max_length=3, null=True),
        ),
    ]
