# Generated by Django 5.2 on 2025-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_formapagamento_alter_movimento_forma'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='icone',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
