# Generated by Django 5.2 on 2025-05-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_formapagamento_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
