# Generated by Django 5.2 on 2025-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(max_length=255)),
                ('codigo_produto', models.CharField(max_length=4)),
                ('codigo_fornecedor', models.CharField(max_length=16)),
                ('situacao', models.CharField(choices=[('P', 'Pendente'), ('E', 'Efetivada'), ('R', 'Recusada'), ('C', 'Concluída')], default='P', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
