# Generated by Django 5.2 on 2025-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='categoria_produto',
            field=models.CharField(choices=[('MOT', 'MOTOR'), ('CEN', 'CENTRAL'), ('CAM', 'CAMERA'), ('PEÇ', 'PEÇA'), ('DVR', 'DVR'), ('NIF', 'NÃO INFORMADO')], default='NÃO INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='fabricante_produto',
            field=models.CharField(choices=[('PPA', 'PPA'), ('ACT', 'ACTON'), ('HIK', 'HIKVISION'), ('MKN', 'MKN'), ('AGL', 'AGL'), ('NIF', 'NÃO INFORMADO')], default='NÃO INFORMADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='situacao',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado'), ('C', 'Concluído')], default='P', max_length=1),
        ),
    ]
