# Generated by Django 5.2 on 2025-04-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_categoria_produto_compra_fabricante_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='categoria_produto',
            field=models.CharField(choices=[('MOT', 'MOTOR'), ('CEN', 'CENTRAL'), ('CAM', 'CAMERA'), ('PEÇ', 'PEÇA'), ('DVR', 'DVR'), ('NIF', 'NÃO INFORMADO')], default='NIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fabricante_produto',
            field=models.CharField(choices=[('PPA', 'PPA'), ('ACT', 'ACTON'), ('HIK', 'HIKVISION'), ('MKN', 'MKN'), ('AGL', 'AGL'), ('NIF', 'NÃO INFORMADO')], default='NIF', max_length=20),
        ),
    ]
