# Generated by Django 5.2 on 2025-04-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_categoria_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='excluido_em',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='categoria_produto',
            field=models.CharField(choices=[('MOT', 'MOTOR'), ('CEN', 'CENTRAL'), ('CAM', 'CAMERA'), ('PEÇ', 'PEÇA'), ('DVR', 'DVR'), ('FON', 'FONTE'), ('SEN', 'SENSOR'), ('OUT', 'OUTROS')], default='NIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fabricante_produto',
            field=models.CharField(choices=[('PPA', 'PPA'), ('ACT', 'ACTON'), ('HIK', 'HIKVISION'), ('GIG', 'GIGA'), ('MKN', 'MKN'), ('MCM', 'MCM'), ('AGL', 'AGL'), ('FC', 'FONTE CFTV'), ('TEM', 'TEM'), ('OUT', 'OUTROS')], default='NIF', max_length=20),
        ),
    ]
