# Generated by Django 5.2 on 2025-04-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_compra_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='codigo_fornecedor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
